
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE `box` ( `box_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `created` bigint(20) NOT NULL, `modified` bigint(20) NOT NULL, `imei` varchar(45) DEFAULT NULL, PRIMARY KEY (`box_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `endpoint` ( `endpoint_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `enabled` bit(1) NOT NULL, `receive_all_boxes` bit(1) NOT NULL, `receive_all_fields` bit(1) NOT NULL, `created` bigint(20) NOT NULL, `modified` bigint(20) NOT NULL, `profile_id` int(10) unsigned DEFAULT NULL, `name` varchar(64) NOT NULL, `apikey` varchar(64) NOT NULL, `url` varchar(256) NOT NULL, `basic_auth` varchar(256) DEFAULT NULL, PRIMARY KEY (`endpoint_id`), UNIQUE KEY `name_UNIQUE` (`name`), KEY `fk_endpoint_profile_idx` (`profile_id`), CONSTRAINT `fk_endpoint_profile` FOREIGN KEY (`profile_id`) REFERENCES `profile` (`profile_id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `field` ( `field_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `name` varchar(32) NOT NULL, PRIMARY KEY (`field_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `lnk_endpoint_box` ( `box_id` int(10) unsigned NOT NULL, `endpoint_id` int(10) unsigned NOT NULL, PRIMARY KEY (`box_id`,`endpoint_id`), KEY `fk_lau_app_idx` (`endpoint_id`), CONSTRAINT `fk_leu_box` FOREIGN KEY (`box_id`) REFERENCES `box` (`box_id`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `fk_leu_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoint` (`endpoint_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `lnk_profile_field` ( `profile_id` int(10) unsigned NOT NULL, `field_id` int(10) unsigned NOT NULL, PRIMARY KEY (`profile_id`,`field_id`), KEY `fk_lpf_field_idx` (`field_id`), CONSTRAINT `fk_lpf_field` FOREIGN KEY (`field_id`) REFERENCES `field` (`field_id`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `fk_lpf_profile` FOREIGN KEY (`profile_id`) REFERENCES `profile` (`profile_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `profile` ( `profile_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `enabled` bit(1) NOT NULL, `name` varchar(64) NOT NULL, `created` bigint(20) NOT NULL, `modified` bigint(20) NOT NULL, PRIMARY KEY (`profile_id`), UNIQUE KEY `name_UNIQUE` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;
